### ISSUE TITLE
create-react-app build fails when minifying this package

### ISSUE THREAD

**Issue by ardalann** [dunckr/email-obfuscate#6]
Steps to replicate:
1. Install [create-react-app](https://github.com/facebookincubator/create-react-app) and create a project
1. Install email-obfuscate in the project
1. `npm run build`

You will get this error and the build fails:
```
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/email-obfuscate/src/text.js:1

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
```

I know you're probably not maintaining this package anymore. But I thought others who want to use it should be aware of this issue.

**Comment by dunckr** [comment]
Fix and deployed new version.

Ty for feedback @ardalann
